export enum SocketEvent {
  CONNECTION_ESTABLISHED = "CONNECTION_ESTABLISHED",
  DISCONNECTED = "DISCONNECTED",
  CONNECTED = "CONNECTED",
  HELLO = "HELLO",
  INVITATION = "INVITATION",
  DELETE_CHAT = "DELETE_CHAT",
  MESSAGE = "MESSAGE",
  MESSAGE_DELETED = "MESSAGE_DELETED",
  PARTICIPANT_ADDED = "PARTICIPANT_ADDED",
  DELETE_GROUP = "DELETE_GROUP",
}
